### ISSUE TITLE
some question about fit process

### ISSUE THREAD

**Issue by liubc-ai** [mks0601/ExAvatar_RELEASE#17]
Dear Author，
Thanks for sharing the awesome project，when I run fit.py, I found in some frame the smplx_optimized behave worse than smplx_init, and accur some strange results, like below:
![0_smplx](https://github.com/user-attachments/assets/35dd60bc-08ec-4867-9e28-c42c21594a56)
but indeed have some perfect results, like below:
![21_smplx](https://github.com/user-attachments/assets/cb02a98e-b8c2-4718-b5d5-4f609aa27978)
 Could you give me some hint ?

**Comment by mks0601** [comment]
I haven't seen such a failure case.. could you check keypoints_whole_body of the failed frame?

**Comment by liubc-ai** [comment]
I found the keypoints is correct and smpl_init is also not bad, so I‘m very confused.

**Comment by mks0601** [comment]
Did you change some code? Could you use up-to-date code and start the whole process from scratch after removing all the dumped outputs?

**Comment by mks0601** [comment]
Sorry I think I found the bug. I saved `kpt` instead of `kpt_save` in [this code](https://github.com/mks0601/ExAvatar_RELEASE/blob/62db97b4c923b1bf9e4b0efe9825506e2bdd0a7f/fitting/tools/code_to_copy/run_mmpose.py#L47), which is wrong. I changed the code to save `kpt_save`. could you run mmpose again with new run_mmpose.py and run fit.py based on the new mmpose results?

**Comment by liubc-ai** [comment]
Thanks for your kind reply, I will try it and give you back

**Comment by liubc-ai** [comment]
After fix the code you metioned, the result is really good, thanks for kind reply.
