### ISSUE TITLE
loaded state dict has a different number of parameter groups

### ISSUE THREAD

**Issue by XingFen-Xie** [mks0601/ExAvatar_RELEASE#5]
Hi,thanks for sharing. There were some errors when I running the code, regarding the Test and evaluation section. `python train.py --subject_id bike --fit_pose_to_test --continue` . 
Then the following error occurs
```Traceback (most recent call last):
  File "train.py", line 85, in <module>
    main()
  File "train.py", line 22, in main
    trainer._make_model()
  File "/New/ExAvatar_RELEASE/avatar/main/../common/base.py", line 136, in _make_model
    optimizer.load_state_dict(ckpt['optimizer'])# strict=False
  File "/root/miniconda3/envs/exavatar/lib/python3.8/site-packages/torch/optim/optimizer.py", line 166, in load_state_dict
    raise ValueError("loaded state dict has a different number of "
ValueError: loaded state dict has a different number of parameter groups
```
and found 
```
(Pdb) len(optimizer.param_groups) 936 
(Pdb) len(ckpt['optimizer']['param_groups']) 954
```
 what should I do to fix it. thanks a lot!

**Comment by omniumai357** [comment]
The error "loaded state dict has a different number of parameter groups" occurs because the optimizer you're trying to load from the checkpoint (ckpt['optimizer']) has a different number of parameter groups compared to the current optimizer (optimizer). Here are some ways to fix this:

1. Don't Load the Optimizer:

If you only care about the model weights and not resuming the training process, you can simply remove the line optimizer.load_state_dict(ckpt['optimizer']). This will load the model weights but not the optimizer state. You'll need to create a new optimizer with the desired parameters.
2. Modify the Code to Handle Different Parameter Groups (Advanced):

This approach involves manually matching parameters between the checkpoint and the current model. It might be a bit complex, but here's a general idea:
Loop through ckpt['optimizer']['param_groups'].
For each group, compare its parameters with the current model parameters based on names or some unique identifier.
If a match is found, update the corresponding group in the current optimizer with the state from the checkpoint.
This approach requires a good understanding of your model structure and the way parameters are grouped.
3. Recreate the Optimizer with the Same Configuration:

If you know the configuration of the optimizer used during training (e.g., learning rate, weight decay, etc.), you can recreate it with the same settings. This ensures the optimizer matches the structure of the loaded model parameters.
Here are some additional points to consider:

Check the code for creating the optimizer in your training script. You can try to recreate the same optimizer with the same configurations when resuming training.
If the difference in parameter groups is due to adding/removing layers in your model, then option 1 (not loading the optimizer) might be the best solution.
Recommendation:

For most cases, option 1 is the simplest solution.  If you specifically need to resume training with the optimizer state, then consider option 3 (recreating the optimizer) or explore advanced techniques like modifying the code to handle different parameter groups (option 2).

**Comment by mks0601** [comment]
@omniumai357  Great thanks for your detailed answer! Like @omniumai357  said, I recommend not loading optimizer. I edited common/base.py like [here](https://github.com/mks0601/ExAvatar_RELEASE/blob/f506f6a3b1e9299682afab184ba72a04061fef8c/avatar/common/base.py#L135).

BTW, why you commend out strict=False? I recommend using it.

**Comment by XingFen-Xie** [comment]
Thanks for the reply! I'll try it as suggested.
